imports:
  - { resource: parameters.yml }
    
services:

  process: 
    class: Symfony\Component\Process\Process
    arguments: [null]
    
  mailer: 
    class: Theapi\Robocop\EmailSender
    arguments: [%email%]
    
  images: 
    class: Theapi\Robocop\Images
    arguments: [%save_dir%, %images%, @process]
    
  mail_parser: 
    class: Theapi\Robocop\MailParser
    arguments: [%save_dir%]
    calls:
      - [ setMailer, [ @mailer ] ]
  