parameters:
  robocop:
    save_dir: /home/cctv
    email:
      from: from@example.com
      to: to@example.com
      host: smtp.example.com
      port: 25
      username: from@example.com
      password: secret
      spool: 1
      spool_dir: /tmp/robocop_spool
    images:
      diff_threshold: 600
      
services:
  mailer: 
    class: Theapi\Robocop\EmailSender
    arguments: [%config%]
  images: 
    class: Theapi\Robocop\Images
    arguments: [%config%]
  mail_parser: 
    class: Theapi\Robocop\MailParser
    arguments: [%config%]
    calls:
      - [ setMailer, [ @mailer ] ]
  