#!/usr/bin/env php
<?php


define('ROBOCOP_PHP_BIN_PATH', getenv('PHP_PEAR_PHP_BIN') ?: '/usr/bin/env php');
define('ROBOCOP_BIN_PATH',     __FILE__);
define('ROBOCOP_VERSION',      'DEV');

function includeIfExists($file)
{
    if (file_exists($file)) {
        return include $file;
    }
}

if ((!$loader = includeIfExists(__DIR__.'/../vendor/autoload.php')) && (!$loader = includeIfExists(__DIR__.'/../../../autoload.php'))) {
    die(
        'You must set up the project dependencies, run the following commands:'.PHP_EOL.
        'curl -s http://getcomposer.org/installer | php'.PHP_EOL.
        'php composer.phar install'.PHP_EOL
    );
}

$app = new Theapi\Robocop\Console\InboxApplication(ROBOCOP_VERSION);
$app->run();